name: C/C++ Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libsdl2-dev

    - name: Build
      run: |
        cmake -Bbuild -H.
        cmake --build build -- -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
